server:
  port: 8080
spring:
  application:
    name: spring-boot-jpa
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jpa
    username: root
    password: root
  #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
  #Redis配置
  redis:
    database: 0
    port: 6379
    host: 192.168.216.142